language: cpp

os:
  - linux
  - osx

dist: focal
osx_image: xcode12

addons:
  homebrew:
    packages:
      - ninja
      - clang-format
  apt:
    packages:
      - ninja-build
      - clang-format

script:
  - echo $PATH
  - which clang-format-10
  - clang-format-10 --version
  - cksum sizeof/has_memfn/solution.h
  # beware of a clang-format 7.0 at front of PATH in Travis!
  - env CLANG_FORMAT=clang-format-10 hack/hack fmt
  - cksum sizeof/has_memfn/solution.h
  - git diff --exit-code
  - hack/hack gen Debug build.debug
  - hack/hack build build.debug
