language: cpp

os:
  - linux
  - osx

dist: focal
osx_image: xcode12

addons:
  homebrew:
    packages:
      - ninja
      - clang-format
  apt:
    packages:
      - ninja-build
      - clang-format

script:
  - which clang-format
  - clang-format --version
  - cksum sizeof/has_memfn/solution.h
  - hack/hack fmt
  - cksum sizeof/has_memfn/solution.h
  - git diff --exit-code
  - hack/hack gen Debug build.debug
  - hack/hack build build.debug
