language: cpp

os:
  - linux
  - osx

dist: focal
osx_image: xcode12

addons:
  homebrew:
    packages:
      - ninja
  apt:
    packages:
      - ninja-build

script:
  - hack/hack gen Debug build.debug
  - hack/hack build build.debug
